import _ from 'lodash';

const noFantasyProPlayerMap = {
  "Jay Ajayi": 0,
  "Rob Gronkowski": 0,
  "Chris Herndon": 0,
  "Michael Crabtree": 0,
  "Jonathan Stewart": 0,
  "Mike Gillislee": 0,
  "Julius Thomas": 0,
  "Chris Johnson": 0,
  "Mike Wallace": 0,
  "Austin Seferian-Jenkins": 0,
  "Matt Forte": 0,
  "DeMarco Murray": 0,
  "Pierre Garcon": 0,
  "Jamaal Charles": 0,
  "Isaiah Crowell": 0,
  "Dez Bryant": 0,
  "Martavis Bryant": 0,
  "Martellus Bennett": 0,
  "Eddie Lacy": 0,
  "Danny Woodhead": 0,
  "Jeremy Hill": 0,
  "Charcandrick West": 0,
  "Brandon Marshall": 0,
  "Rishard Matthews": 0,
  "Kelvin Benjamin": 0,
  "Kenny Britt": 0,
  "Stevan Ridley": 0,
  "Mike Tolbert": 0,
  "Erik Swoope": 0,
  "Alex Collins": 0,
  "Darrius Heyward-Bey": 0,
  "De'Anthony Thomas": 0,
  "Zach Miller": 0,
  "Rob Kelley": 0,
  "Jeremy Kerley": 0,
  "Marshawn Lynch": 0,
  "LeGarrette Blount": 0,
  "Jordy Nelson": 0,
  "Darren McFadden": 0,
  "Chris Ivory": 0
}

const espnPlayerToFantasyProsPlayerMap = {
  "Duke Johnson Jr.":  "Duke Johnson",
  "Will Fuller V": "Will Fuller",
  "DJ Moore": "D.J. Moore",
  "DK Metcalf": "D.K. Metcalf",
  "Marvin Jones Jr.": "Marvin Jones",
  "Mark Ingram II": "Mark Ingram",
  "Mitchell Trubisky": "Mitch Trubisky",
  "Todd Gurley II": "Todd Gurley",
  "Terrelle Pryor Sr.": "Terrelle Pryor",
  "Willie Snead IV": "Willie Snead",
  "Ted Ginn Jr.": "Ted Ginn",
  "John Ross III": "John Ross",
  "Robert Griffin III": "Robert Griffin",
  "Ronald Jones": "Ronald Jones II",
  "Mike Badgley": "Michael Badgley",
  "DeVante Parker": "Devante Parker",

  '49ers D/ST': 'San Francisco 49ers',
  'Bears D/ST': 'Chicago Bears',
  'Bengals D/ST': 'Cincinnati Bengals',
  'Bills D/ST': 'Buffalo Bills',
  'Broncos D/ST': 'Denver Broncos',
  'Browns D/ST': 'Cleveland Browns',
  'Buccaneers D/ST': 'Tampa Bay Buccaneers',
  'Cardinals D/ST': 'Arizona Cardinals',
  'Chargers D/ST': 'Los Angeles Chargers',
  'Chiefs D/ST': 'Kansas City Chiefs',
  'Colts D/ST': 'Indianapolis Colts',
  'Cowboys D/ST': 'Dallas Cowboys',
  'Dolphins D/ST': 'Miami Dolphins',
  'Eagles D/ST': 'Philadelphia Eagles',
  'Falcons D/ST': 'Atlanta Falcons',
  'Giants D/ST': 'New York Giants',
  'Jaguars D/ST': 'Jacksonville Jaguars',
  'Jets D/ST': 'New York Jets',
  'Lions D/ST': 'Detroit Lions',
  'Packers D/ST': 'Green Bay Packers',
  'Panthers D/ST': 'Carolina Panthers',
  'Patriots D/ST': 'New England Patriots',
  'Raiders D/ST': 'Oakland Raiders',
  'Rams D/ST': 'Los Angeles Rams',
  'Ravens D/ST': 'Baltimore Ravens',
  'Redskins D/ST': 'Washington Redskins',
  'Saints D/ST': 'New Orleans Saints',
  'Seahawks D/ST': 'Seattle Seahawks',
  'Steelers D/ST': 'Pittsburgh Steelers',
  'Texans D/ST': 'Houston Texans',
  'Titans D/ST': 'Tennessee Titans',
  'Vikings D/ST': 'Minnesota Vikings'
}

const fantasyProsPlayerToEspnPlayerMap = _.invert(espnPlayerToFantasyProsPlayerMap);


export {
  espnPlayerToFantasyProsPlayerMap,
  fantasyProsPlayerToEspnPlayerMap
};